### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by jmhendricks1** [erikerhardt/flipMaxDiff#1]
Trying to install flipMaxDiff and I keep getting the same error code: 

Error: object ‘TrimWhitespace’ is not exported by 'namespace:flipFormat'
Execution halted

Any thoughts on why?

**Comment by erikerhardt** [comment]
I do not know.  I forked the package from https://rdrr.io/github/google/GeoexperimentsResearch/, they may be able to answer your question.
